import agentSttSidebar from "./agent-stt/sidebar";
import preRecordedSidebar from "./pre-recorded/sidebar";
import streamingSidebar from "./streaming/sidebar";

export default {
  type: "category",
  label: "Speech to Text",
  collapsible: false,
  collapsed: false,
  items: [
    {
      type: "doc",
      id: "speech-to-text/index",
      label: "Overview",
    },
    {
      type: "doc",
      id: "speech-to-text/interaction-patterns",
    },
    // Order follows the Level 1 sequence in product-architecture.md:
    // pre-recorded, streaming, then agent STT.
    preRecordedSidebar,
    streamingSidebar,
    agentSttSidebar,
    {
      type: "doc",
      id: "speech-to-text/models",
    },
    {
      type: "doc",
      id: "speech-to-text/languages/index",
    },
    {
      type: "doc",
      id: "speech-to-text/languages/transcription",
    },
    {
      // Declared explicitly rather than autogenerated: sidebar-generator.ts
      // title-cases autogenerated category labels word by word.
      type: "category",
      label: "Availability",
      items: [
        {
          type: "doc",
          id: "speech-to-text/availability/index",
        },
        {
          type: "doc",
          id: "speech-to-text/availability/on-prem",
        },
      ],
    },
    {
      // Declared explicitly rather than autogenerated: sidebar-generator.ts
      // title-cases autogenerated category labels word by word.
      type: "category",
      label: "Features",
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text/features",
        },
      ],
    },
    {
      type: "category",
      label: "Add-ons",
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text/add-ons",
        },
      ],
    },
    {
      type: "doc",
      label: "Accuracy benchmarking",
      id: "speech-to-text/accuracy-benchmarking",
    },
  ],
};
