import batchSidebar from "./batch-transcription/sidebar";
import realtimeSidebar from "./real-time-transcription/sidebar";

export default {
  type: "category",
  label: "Speech to Text",
  collapsible: false,
  collapsed: false,
  items: [
    {
      type: "doc",
      id: "speech-to-text/index",
      label: "Overview",
    },
    batchSidebar,
    realtimeSidebar,
    {
      type: "doc",
      id: "speech-to-text/supported-languages",
    },
    {
      type: "doc",
      id: "speech-to-text/translation",
    },
    {
      type: "category",
      label: "Features",
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text/features",
        },
      ],
    },
    {
      type: "category",
      label: "Output Enhancements",
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text/output-enhancements",
        },
      ],
    },
    {
      type: "doc",
      id: "speech-to-text/accuracy-benchmarking",
    },
  ],
};
