export default {
  type: "category",
  label: "Real-Time Transcription",
  items: [
    {
      type: "autogenerated",
      dirName: "speech-to-text/real-time",
    },
    {
      type: "link",
      label: "API Reference",
      href: "/api-ref/realtime-transcription-websocket",
    },
  ],
} as const;
