export default {
  type: "category",
  label: "Real-Time Transcription",
  items: [
    {
      type: "doc",
      id: "speech-to-text/real-time/quickstart",
    },
    {
      type: "doc",
      id: "speech-to-text/real-time/input",
    },
    {
      type: "doc",
      id: "speech-to-text/real-time/output",
    },
    {
      type: "doc",
      id: "speech-to-text/real-time/latency",
    },
    {
      type: "doc",
      id: "speech-to-text/real-time/end-of-turn",
    },
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text/real-time/guides",
        },
      ],
    },
    {
      type: "link",
      label: "API Reference",
      href: "/api-ref/realtime-transcription-websocket",
    },
  ],
} as const;
