export default {
  type: "category",
  label: "Voice agents – Flow",
  collapsible: false,
  collapsed: false,
  items: [
    {
      type: "autogenerated",
      dirName: "voice-agents-flow",
    },
  ],
} as const;
