export default {
  type: "category",
  label: "Voice agents – Flow",
  collapsible: false,
  collapsed: false,
  items: [
    {
      type: "doc",
      id: "voice-agents-flow/index",
    },
    {
      type: "category",
      label: "Features",
      items: [
        {
          type: "autogenerated",
          dirName: "voice-agents-flow/features",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "voice-agents-flow/guides",
        },
        {
          type: "doc",
          id: "guides/projects",
        },
      ],
    },
    {
      type: "doc",
      id: "voice-agents-flow/setup",
    },
    {
      type: "doc",
      id: "voice-agents-flow/supported-formats-and-limits",
    },

    {
      type: "doc",
      id: "voice-agents-flow/supported-languages",
    },
  ],
} as const;
