export default {
  type: "category",
  label: "Container",
  collapsible: true,
  collapsed: true,
  items: [
    {
      type: "autogenerated",
      dirName: "deployments/container",
    },
  ],
};
