export default {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "index",
          label: "Welcome",
        },
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },
    {
      type: "category",
      label: "Speech to Text",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text",
        },
      ],
    },
    {
      type: "category",
      label: "Voice Agents Flow",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "voice-agents-flow",
        },
      ],
    },
    {
      type: "category",
      label: "Deployments",
      collapsible: false,
      collapsed: false,
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "deployments",
        },
      ],
    },
    {
      type: "category",
      label: "Developer Resources",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "link",
          href: "https://github.com/speechmatics",
          label: "GitHub",
        },
      ],
    },
  ],
  apiRefSidebar: [
    {
      type: "category",
      collapsible: false,
      collapsed: false,
      label: "General",
      items: [
        {
          type: "doc",
          id: "api-ref/index",
          label: "Introduction",
        },
      ],
    },
    {
      type: "category",
      collapsible: false,
      collapsed: false,
      label: "Jobs API",
      link: {
        type: "generated-index",
        title: "Jobs API",
        slug: "/category/jobs-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "api-ref/jobs",
        },
      ],
    },
    {
      type: "category",
      collapsible: false,
      collapsed: false,
      label: "Real-time transcription",
      items: [
        {
          type: "doc",
          id: "api-ref/realtime",
          label: "Start transcription",
          className: "wss api-method",
        },
      ],
    },
  ],
};
