export default {
  type: "category",
  label: "Batch transcription",
  items: [
    {
      type: "doc",
      id: "speech-to-text/batch/quickstart",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/input",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/output",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/limits",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/batch-diarization",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/speaker-identification",
    },
    {
      type: "category",
      label: "Speech intelligence",
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text/batch/speech-intelligence",
        },
      ],
    },
    {
      type: "doc",
      id: "speech-to-text/batch/notifications",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/language-identification",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/srt-format",
    },
    // TODO see about usage requests
    // {
    //   type: "doc",
    //   id: "speech-to-text/batch/usage-requests",
    // },
    {
      type: "doc",
      id: "speech-to-text/batch/troubleshooting",
    },
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "doc",
          id: "guides/projects",
        },
      ],
    },
    {
      type: "link",
      href: "/api-ref/batch/create-a-new-job",
      label: "API reference",
    },
  ],
} as const;
