export default {
  type: "category",
  label: "Batch Transcription",
  items: [
    {
      type: "doc",
      id: "speech-to-text/batch/index",
      label: "Overview",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/quickstart",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/supported-files-and-limits",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/check-job-status",
    },
    {
      type: "category",
      label: "Speech Intelligence",
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text/batch/speech-intelligence",
        },
      ],
    },
    {
      type: "doc",
      id: "speech-to-text/batch/notifications",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/fetch-url",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/language-identification",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/alignment",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/srt-format",
    },
    {
      type: "doc",
      id: "speech-to-text/batch/tracking",
    },
    // TODO see about usage requests
    // {
    //   type: "doc",
    //   id: "speech-to-text/batch/usage-requests",
    // },
    {
      type: "doc",
      id: "speech-to-text/batch/troubleshooting",
    },
    {
      type: "link",
      href: "/api-ref/batch/create-a-new-job",
      label: "API Reference",
    },
  ],
} as const;
