export default {
  type: "category",
  label: "Text to speech",
  collapsible: false,
  collapsed: false,
  items: [
    {
      type: "autogenerated",
      dirName: "text-to-speech",
    },
  ],
} as const;
