// Declared explicitly rather than autogenerated: sidebar-generator.ts
// title-cases autogenerated category labels word by word, which would
// render "agent-stt" as "Agent Stt".
export default {
  type: "category",
  label: "Agent STT",
  items: [
    {
      type: "doc",
      id: "speech-to-text/agent-stt/index",
    },
    {
      type: "doc",
      id: "speech-to-text/agent-stt/quickstart",
    },
    {
      type: "doc",
      id: "speech-to-text/agent-stt/profiles",
    },
    {
      type: "doc",
      id: "speech-to-text/agent-stt/configuration",
    },
    {
      type: "doc",
      id: "speech-to-text/agent-stt/messages",
    },
    {
      type: "doc",
      id: "speech-to-text/agent-stt/speaker-focus",
    },
  ],
} as const;
