export default {
  type: "category",
  label: "Getting Started",
  collapsible: false,
  collapsed: false,
  items: [
    {
      type: "doc",
      id: "index",
      label: "Welcome",
    },
    {
      type: "autogenerated",
      dirName: "getting-started",
    },
    {
      type: "link",
      href: "https://www.speechmatics.com/pricing",
      label: "Pricing",
    },
  ],
} as const;
