export default {
  type: "category",
  label: "Realtime Transcription",
  items: [
    {
      type: "doc",
      id: "speech-to-text/realtime/quickstart",
    },
    {
      type: "doc",
      id: "speech-to-text/realtime/input",
    },
    {
      type: "doc",
      id: "speech-to-text/realtime/output",
    },
    {
      type: "doc",
      id: "speech-to-text/realtime/limits",
    },
    {
      type: "doc",
      id: "speech-to-text/realtime/realtime-diarization",
    },
    {
      type: "doc",
      id: "speech-to-text/realtime/realtime-speaker-identification",
    },
    {
      type: "doc",
      id: "speech-to-text/realtime/end-of-utterance",
    },
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text/realtime/guides",
        },
        {
          type: "doc",
          id: "guides/projects",
        },
      ],
    },
    {
      type: "link",
      label: "API reference",
      href: "/api-ref/realtime-transcription-websocket",
    },
  ],
} as const;
