export default [
  {
    type: "category",
    label: "Virtual Appliance",
    items: [
      {
        type: "autogenerated",
        dirName: "deployments/virtual-appliance",
      },
    ],
  },
];
