export default [
  {
    type: "category",
    label: "Virtual Appliance",
    items: [
      {
        type: "doc",
        label: "Overview",
        id: "deployments/virtual-appliance/index",
      },
      {
        type: "category",
        label: "Installation",
        items: [
          {
            type: "autogenerated",
            dirName: "deployments/virtual-appliance/installation",
          },
        ],
      },
      {
        type: "category",
        label: "Administration",
        items: [
          {
            type: "autogenerated",
            dirName: "deployments/virtual-appliance/administration",
          },
        ],
      },
    ],
  },
];
