/**
 * Generates spec/agent-stt.yaml from the Agent STT JSON Schema files in the
 * openapi-specifications repo, merged with the hand-written parts in
 * spec/agent-stt.overlay.yaml.
 *
 * The openapi-specifications repo is not a dependency of this repo, so this
 * script is run manually and its output committed — the same arrangement as
 * spec/realtime.yaml. Pass the source directory as the first argument, or set
 * AGENT_STT_SPEC_DIR, if the repo is not checked out alongside this one.
 *
 *   npm run build:agent-stt-spec
 *   npm run build:agent-stt-spec -- ../some/other/auto-generated
 */

import { readFileSync, writeFileSync } from "node:fs";
import { Parser } from "@asyncapi/parser";
import yaml from "yaml";

const DEFAULT_SPEC_DIR = "../openapi-specifications/auto-generated";
const INPUT_FILE = "agent-transcription-websocket-v2-input.json";
const OUTPUT_FILE = "agent-transcription-websocket-v2-output.json";
const OVERLAY_PATH = "spec/agent-stt.overlay.yaml";
const TARGET_PATH = "spec/agent-stt.yaml";

type JsonSchema = Record<string, unknown>;

interface SourceSpec {
  definitions: Record<string, JsonSchema>;
  oneOf: { $ref: string }[];
}

interface Overlay {
  info: Record<string, unknown>;
  servers: Record<string, unknown>;
  omitProperties?: Record<string, string[]>;
  descriptions?: Record<string, Record<string, string>>;
  summaries?: Record<string, string>;
  extraMessages?: Record<
    "publish" | "subscribe",
    Record<
      string,
      {
        after?: string;
        summary: string;
        contentType?: string;
        schema: JsonSchema;
      }
    >
  >;
}

const specDir =
  process.argv[2] ?? process.env.AGENT_STT_SPEC_DIR ?? DEFAULT_SPEC_DIR;

const overlay: Overlay = yaml.parse(readFileSync(OVERLAY_PATH, "utf8"));
const input = readSource(`${specDir}/${INPUT_FILE}`);
const output = readSource(`${specDir}/${OUTPUT_FILE}`);

// Both files define their own copies of the shared schemas, so collect them
// into one namespace and fail loudly if the two ever disagree.
const schemas: Record<string, JsonSchema> = {};
for (const [source, { definitions }] of [
  ["input", input],
  ["output", output],
] as const) {
  for (const [name, schema] of Object.entries(definitions)) {
    const converted = rewriteRefs(schema) as JsonSchema;
    const existing = schemas[name];
    if (existing && JSON.stringify(existing) !== JSON.stringify(converted)) {
      throw new Error(
        `Schema "${name}" is defined differently in the input and output specs. ` +
          `Resolve the conflict upstream before regenerating (found while reading the ${source} spec).`,
      );
    }
    schemas[name] = converted;
  }
}

applyOverlayToSchemas();

const messages: Record<string, JsonSchema> = {};
const channels = {
  publish: { address: "/", messages: {} as Record<string, JsonSchema> },
  subscribe: { address: "/", messages: {} as Record<string, JsonSchema> },
};

buildChannel("publish", messageNames(input));
buildChannel("subscribe", messageNames(output));

const document = {
  asyncapi: "3.0.0",
  id: "urn:com:speechmatics:agent-stt-api",
  defaultContentType: "application/json",
  info: overlay.info,
  servers: overlay.servers,
  channels,
  operations: {
    publish: {
      action: "send",
      channel: { $ref: "#/channels/publish" },
      messages: Object.keys(channels.publish.messages).map((name) => ({
        $ref: `#/channels/publish/messages/${name}`,
      })),
    },
    subscribe: {
      action: "receive",
      channel: { $ref: "#/channels/subscribe" },
      messages: Object.keys(channels.subscribe.messages).map((name) => ({
        $ref: `#/channels/subscribe/messages/${name}`,
      })),
    },
  },
  components: {
    messages,
    // Sorted so an upstream change produces a diff of that change alone.
    schemas: Object.fromEntries(
      Object.entries(schemas).sort(([a], [b]) => a.localeCompare(b)),
    ),
  },
};

(async () => {
  await validate(document);

  const header = `# DO NOT EDIT — generated by scripts/generate-agent-stt-spec.ts.
#
# Source: ${INPUT_FILE}
#         ${OUTPUT_FILE}
#         (openapi-specifications repo, auto-generated/)
#
# Message summaries, servers and the binary AddAudio message come from
# ${OVERLAY_PATH}. Edit that file, then run \`npm run build:agent-stt-spec\`.

`;

  writeFileSync(
    TARGET_PATH,
    header + yaml.stringify(document, { lineWidth: 0 }),
  );
  console.log(
    `Wrote ${TARGET_PATH}: ${Object.keys(channels.publish.messages).length} sent and ` +
      `${Object.keys(channels.subscribe.messages).length} received messages, ` +
      `${Object.keys(schemas).length} schemas.`,
  );
})();

function readSource(path: string): SourceSpec {
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch {
    throw new Error(
      `Could not read ${path}. Check out the openapi-specifications repo alongside this one, or pass its auto-generated directory as an argument.`,
    );
  }

  const spec = JSON.parse(raw);
  if (!spec.definitions || !Array.isArray(spec.oneOf)) {
    throw new Error(
      `${path} has no "definitions" or no top-level "oneOf" — has the format changed?`,
    );
  }
  return spec;
}

/**
 * Applies the overlay's `omitProperties` and `descriptions` to the schemas
 * collected from the source spec. Both exist because the source is shared with
 * other products: it carries fields we do not expose in the published API
 * reference, and prose that refers to them.
 */
function applyOverlayToSchemas() {
  for (const [name, properties] of Object.entries(
    overlay.omitProperties ?? {},
  )) {
    for (const property of properties) {
      omitProperty(schemaFor(name, "omitProperties"), name, property);
    }
  }

  for (const [name, descriptions] of Object.entries(
    overlay.descriptions ?? {},
  )) {
    const schema = schemaFor(name, "descriptions");
    const properties = (schema.properties ?? {}) as Record<string, JsonSchema>;
    for (const [property, description] of Object.entries(descriptions)) {
      if (!properties[property]) {
        throw new Error(
          `Overlay descriptions entry "${name}.${property}" does not match a property in the source schema.`,
        );
      }
      properties[property].description = description;
    }
  }
}

function schemaFor(name: string, section: string): JsonSchema {
  const schema = schemas[name];
  if (!schema) {
    throw new Error(
      `Overlay ${section} names schema "${name}", which the source spec does not define.`,
    );
  }
  return schema;
}

/**
 * Removes a property from a schema, along with the constraints that reference
 * it: `required` entries, and `allOf` / `anyOf` / `oneOf` branches. An `anyOf`
 * or `oneOf` left with a single `required` branch is folded into the schema's
 * own `required`, since a one-branch choice is no choice at all.
 */
function omitProperty(schema: JsonSchema, name: string, property: string) {
  const properties = (schema.properties ?? {}) as Record<string, JsonSchema>;
  if (!properties[property]) {
    throw new Error(
      `Overlay omitProperties entry "${name}.${property}" does not match a property in the source schema — has it already been removed upstream?`,
    );
  }
  delete properties[property];
  setRequired(
    schema,
    required(schema).filter((item) => item !== property),
  );

  for (const keyword of ["allOf", "anyOf", "oneOf"] as const) {
    const branches = schema[keyword] as JsonSchema[] | undefined;
    if (!branches) continue;

    const kept = branches.filter((branch) => !references(branch, property));
    if (kept.length === branches.length) continue;

    if (keyword !== "allOf" && kept.length === 1) {
      const [branch] = kept;
      if (Object.keys(branch).join() !== "required") {
        throw new Error(
          `Omitting "${name}.${property}" leaves a single ${keyword} branch that is not a plain "required" list. Fold it into ${name} by hand.`,
        );
      }
      setRequired(schema, [
        ...new Set([...required(schema), ...required(branch)]),
      ]);
      delete schema[keyword];
      continue;
    }

    if (kept.length === 0) delete schema[keyword];
    else schema[keyword] = kept;
  }
}

function required(schema: JsonSchema): string[] {
  return (schema.required as string[] | undefined) ?? [];
}

function setRequired(schema: JsonSchema, names: string[]) {
  if (names.length > 0) schema.required = names;
  else Reflect.deleteProperty(schema, "required");
}

/** True if `property` appears anywhere in a schema branch, as a key or a `required` entry. */
function references(node: unknown, property: string): boolean {
  if (Array.isArray(node))
    return node.some((item) => references(item, property));
  if (node === null || typeof node !== "object") return false;

  return Object.entries(node).some(
    ([key, value]) =>
      key === property ||
      (key === "required" &&
        Array.isArray(value) &&
        value.includes(property)) ||
      references(value, property),
  );
}

/** The top-level `oneOf` lists every message the channel carries, in order. */
function messageNames({ oneOf }: SourceSpec): string[] {
  return oneOf.map(({ $ref }) => {
    const name = $ref?.replace("#/definitions/", "");
    if (!name || !$ref.startsWith("#/definitions/")) {
      throw new Error(
        `Expected a "#/definitions/..." ref in oneOf, got: ${JSON.stringify($ref)}`,
      );
    }
    return name;
  });
}

function buildChannel(channel: "publish" | "subscribe", names: string[]) {
  const extras = overlay.extraMessages?.[channel] ?? {};

  for (const name of names) {
    addMessage(channel, name, {
      summary: summaryFor(name),
      payload: { $ref: `#/components/schemas/${name}` },
    });

    // Place any hand-written message that follows this one.
    for (const [extraName, extra] of Object.entries(extras)) {
      if (extra.after !== name) continue;
      schemas[extraName] = extra.schema;
      addMessage(channel, extraName, {
        summary: extra.summary,
        ...(extra.contentType ? { contentType: extra.contentType } : {}),
        payload: { $ref: `#/components/schemas/${extraName}` },
      });
    }
  }

  const unplaced = Object.entries(extras).filter(
    ([name, extra]) =>
      !(name in channels[channel].messages) &&
      (!extra.after || !names.includes(extra.after)),
  );
  for (const [name, extra] of unplaced) {
    throw new Error(
      `Overlay message "${name}" has after: "${extra.after}", which is not a ${channel} message.`,
    );
  }
}

function addMessage(
  channel: "publish" | "subscribe",
  name: string,
  message: JsonSchema,
) {
  messages[name] = message;
  channels[channel].messages[name] = { $ref: `#/components/messages/${name}` };
}

function summaryFor(name: string): string {
  const summary =
    overlay.summaries?.[name] ??
    (schemas[name]?.description as string | undefined);
  if (!summary) {
    console.warn(
      `Warning: no summary for "${name}". Add one to ${OVERLAY_PATH} — the page renders "No summary" without it.`,
    );
    return "";
  }
  return summary;
}

/** Rewrites draft-07 `#/definitions/X` refs to their AsyncAPI location. */
function rewriteRefs(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(rewriteRefs);
  if (node === null || typeof node !== "object") return node;

  return Object.fromEntries(
    Object.entries(node).map(([key, value]) => {
      if (key === "$ref" && typeof value === "string") {
        return [
          key,
          value.replace(/^#\/definitions\//, "#/components/schemas/"),
        ];
      }
      return [key, rewriteRefs(value)];
    }),
  );
}

async function validate(document: object) {
  const { diagnostics } = await new Parser().parse(yaml.stringify(document));
  const errors = diagnostics.filter(({ severity }) => severity === 0);
  if (errors.length > 0) {
    for (const { message, path } of errors) {
      console.error(`  ${path?.join("/") ?? "(root)"}: ${message}`);
    }
    throw new Error(
      "Generated document is not valid AsyncAPI 3.0 — nothing written.",
    );
  }
}
