export default [
  {
    type: "category",
    collapsible: false,
    collapsed: false,
    label: "General",
    items: [
      {
        type: "doc",
        id: "api-ref/index",
        label: "Introduction",
      },
    ],
  },
  {
    type: "category",
    collapsible: false,
    collapsed: false,
    label: "Transcription API",
    items: [
      {
        type: "doc",
        id: "api-ref/realtime-transcription-websocket",
        label: "Transcribe Realtime audio",
        className: "wss api-method",
      },
      {
        type: "autogenerated",
        dirName: "api-ref/batch",
      },
    ],
  },
] as const;
