export default {
  type: "category",
  label: "LiveKit",
  collapsible: true,
  collapsed: true,
  items: [
    {
      type: "autogenerated",
      dirName: "integrations/livekit",
    },
    {
      type: "doc",
      id: "integrations/livekit/speechmatics-stt-plugin-guide",
      label: "Speechmatics STT Plugin Guide",
    },
    {
      type: "doc",
      id: "integrations/livekit/livekit",
      label: "LiveKit",
    }
  ],
};
