// This file handles redirects that the old docs site has in place from an even earlier version
export const taggedRedirects = [
  {
    to: "/introduction/batch-guide",
    from: ["/en/cloud/howto/", "/en/batch-appliance/api-guide/api-howto/"],
  },
  {
    to: "/features/entities",
    from: [
      "/en/cloud/entities/",
      "/en/real-time-saas/entities/",
      "/en/batch-appliance/entities/",
      "/en/real-time-appliance/entities/",
      "/en/batch-container/entities/",
      "/en/real-time-container/entities/",
    ],
  },
  {
    to: "/jobsapi/",
    from: [
      "/en/cloud/saasv2api/",
      "/en/batch-appliance/api-guide/",
      "/en/batch-appliance/api-guide/api-howto/speech-api/",
      "/en/batch-appliance/error-codes/",
      "/en/real-time-appliance/api-v2/",
    ],
  },
  {
    to: "/introduction/rt-guide",
    from: [
      "/en/real-time-saas/user-guide/",
      "/en/real-time-appliance/api-v2/speech-api-guide/",
      "/en/real-time-appliance/api-v2/api-example-usage/",
      "/en/real-time-saas/",
    ],
  },
  {
    to: "/release-notes/batch-appliance-release-notes",
    from: ["/en/batch-appliance/release-notes/"],
  },
  {
    to: "/release-notes/real-time-appliance-release-notes",
    from: ["/en/real-time-appliance/release-notes/"],
  },
  {
    to: "/on-prem/virtual-appliance/installation",
    from: [
      "/en/batch-appliance/",
      "/en/batch-appliance/install-admin-guide/",
      "/en/batch-appliance/install-admin-guide/introduction/",
      "/en/batch-appliance/install-admin-guide/system-requirements/",
      "/en/batch-appliance/install-admin-guide/downloading/",
      "/en/batch-appliance/install-admin-guide/importing/",
      "/en/batch-appliance/install-admin-guide/networking/",
      "/en/batch-appliance/install-admin-guide/licensing/",
      "/en/batch-appliance/install-admin-guide/goverify-ba/",
      "/en/batch-appliance/install-admin-guide/administration/",
      "/en/batch-appliance/install-admin-guide/administration/ssl/",
      "/en/batch-appliance/install-admin-guide/administration/networking-admin/",
      "/en/batch-appliance/install-admin-guide/administration/scaling/",
      "/en/batch-appliance/install-admin-guide/administration/monitoring-admin/",
      "/en/batch-appliance/install-admin-guide/administration/services/",
      "/en/batch-appliance/install-admin-guide/administration/security/",
      "/en/real-time-appliance/",
      "/en/real-time-appliance/install-admin-guide/",
      "/en/real-time-appliance/install-admin-guide/introduction/",
      "/en/real-time-appliance/install-admin-guide/system-requirements/",
      "/en/real-time-appliance/install-admin-guide/downloading/",
      "/en/real-time-appliance/install-admin-guide/importing/",
      "/en/real-time-appliance/install-admin-guide/networking/",
      "/en/real-time-appliance/install-admin-guide/licensing/",
      "/en/real-time-appliance/install-admin-guide/goverify-rta/",
      "/en/real-time-appliance/install-admin-guide/administration/",
      "/en/real-time-appliance/install-admin-guide/administration/ssl/",
      "/en/real-time-appliance/install-admin-guide/administration/networking-admin/",
      "/en/real-time-appliance/install-admin-guide/administration/scaling/",
      "/en/real-time-appliance/install-admin-guide/administration/monitoring-admin/",
      "/en/real-time-appliance/install-admin-guide/administration/services/",
      "/en/real-time-appliance/install-admin-guide/administration/security/",
      "/en/real-time-appliance/install-admin-guide/administration/cd-cache-admin/",
      "/en/real-time-appliance/demo/",
    ],
  },
  {
    to: "/on-prem/containers/cpu-container",
    from: [
      "/on-prem/container/",
      "/en/batch-container/",
      "/en/batch-container/speech-api/",
      "/en/batch-container/speech-api/parallel-processing/",
      "/en/batch-container/technical-guide-migration/",
      "/en/batch-container/quick-start/",
      "/en/batch-container/demo/",
      "/en/real-time-container/",
      "/en/real-time-container/speech-api/",
      "/en/real-time-container/speech-api/parallel-processing/",
      "/en/real-time-container/technical-guide-migration/",
      "/en/real-time-container/quick-start/",
      "/en/real-time-container/speech-api-guide/",
      "/en/real-time-container/quick-start/health-checks/",
      "/en/real-time-container/quick-start/troubleshooting/",
      "/en/real-time-container/speech-api-guide/api-howto/",
    ],
  },
  {
    to: "/release-notes/batch-container-release-notes",
    from: ["/en/batch-container/release-notes/"],
  },
  {
    to: "/release-notes/real-time-container-release-notes",
    from: ["/en/real-time-container/release-notes/"],
  },
] as const;

// These tags sets are used to avoid long lists of tagged routes
export const tagSets = {
  rtContainer: [
    "2.0.0",
    "1.4.1",
    "1.4.0",
    "1.3.1",
    "1.3.0",
    "1.2.0",
    "1.1.0",
    "1.0.0",
  ],
  batchContainer: [
    "9.0.1",
    "9.0.0",
    "8.2.0",
    "8.1.2",
    "8.1.0",
    "8.0.0",
    "7.0.3",
    "6.3.0",
  ],
  core: [
    "4.2.0",
    "4.1.0",
    "4.0.0",
    "3.8.0",
    "3.7.1",
    "3.7.0",
    "3.6.0",
    "3.5.0",
    "3.4.0",
    "3.3.0",
  ],
} as const;

// maps routes to which set of tags to attach to those routes
export const tagMap = {
  "/en/batch-appliance/": "core",
  "/en/batch-appliance/release-notes/": "core",
  "/en/batch-appliance/install-admin-guide/": "core",
  "/en/batch-appliance/install-admin-guide/introduction/": "core",
  "/en/batch-appliance/install-admin-guide/system-requirements/": "core",
  "/en/batch-appliance/install-admin-guide/downloading/": "core",
  "/en/batch-appliance/install-admin-guide/importing/": "core",
  "/en/batch-appliance/install-admin-guide/networking/": "core",
  "/en/batch-appliance/install-admin-guide/licensing/": "core",
  "/en/batch-appliance/install-admin-guide/goverify-ba/": "core",
  "/en/batch-appliance/install-admin-guide/administration/": "core",
  "/en/batch-appliance/install-admin-guide/administration/ssl/": "core",
  "/en/batch-appliance/install-admin-guide/administration/networking-admin/":
    "core",
  "/en/batch-appliance/install-admin-guide/administration/scaling/": "core",
  "/en/batch-appliance/install-admin-guide/administration/monitoring-admin/":
    "core",
  "/en/batch-appliance/install-admin-guide/administration/services/": "core",
  "/en/batch-appliance/install-admin-guide/administration/security/": "core",
  "/en/batch-appliance/api-guide/": "core",
  "/en/batch-appliance/api-guide/api-howto/": "core",
  "/en/batch-appliance/api-guide/api-howto/speech-api/": "core",
  "/en/batch-appliance/error-codes/": "core",
  "/en/batch-appliance/entities/": "core",
  "/en/real-time-appliance/": "core",
  "/en/real-time-appliance/release-notes/": "core",
  "/en/real-time-appliance/install-admin-guide/": "core",
  "/en/real-time-appliance/install-admin-guide/introduction/": "core",
  "/en/real-time-appliance/install-admin-guide/system-requirements/": "core",
  "/en/real-time-appliance/install-admin-guide/downloading/": "core",
  "/en/real-time-appliance/install-admin-guide/importing/": "core",
  "/en/real-time-appliance/install-admin-guide/networking/": "core",
  "/en/real-time-appliance/install-admin-guide/licensing/": "core",
  "/en/real-time-appliance/install-admin-guide/goverify-rta/": "core",
  "/en/real-time-appliance/install-admin-guide/administration/": "core",
  "/en/real-time-appliance/install-admin-guide/administration/ssl/": "core",
  "/en/real-time-appliance/install-admin-guide/administration/networking-admin/":
    "core",
  "/en/real-time-appliance/install-admin-guide/administration/scaling/": "core",
  "/en/real-time-appliance/install-admin-guide/administration/monitoring-admin/":
    "core",
  "/en/real-time-appliance/install-admin-guide/administration/services/":
    "core",
  "/en/real-time-appliance/install-admin-guide/administration/security/":
    "core",
  "/en/real-time-appliance/install-admin-guide/administration/cd-cache-admin/":
    "core",
  "/en/real-time-appliance/api-v2/": "core",
  "/en/real-time-appliance/api-v2/speech-api-guide/": "core",
  "/en/real-time-appliance/api-v2/api-example-usage/": "core",
  "/en/real-time-appliance/entities/": "core",
  "/en/real-time-appliance/demo/": "core",
  "/en/batch-container/release-notes/": "batchContainer",
  "/en/batch-container/quick-start/": "batchContainer",
  "/en/batch-container/speech-api/": "batchContainer",
  "/en/batch-container/speech-api/parallel-processing/": "batchContainer",
  "/en/batch-container/entities/": "batchContainer",
  "/en/batch-container/technical-guide-migration/": "batchContainer",
  "/en/batch-container/demo/": "batchContainer",
  "/en/real-time-container/release-notes/": "rtContainer",
  "/en/real-time-container/quick-start/": "rtContainer",
  "/en/real-time-container/quick-start/health-checks/": "rtContainer",
  "/en/real-time-container/quick-start/troubleshooting/": "rtContainer",
  "/en/real-time-container/speech-api-guide/": "rtContainer",
  "/en/real-time-container/speech-api-guide/api-howto/": "rtContainer",
  "/en/real-time-container/entities/": "rtContainer",
} as const;
