export default {
  type: "category",
  label: "Streaming transcription",
  items: [
    {
      type: "doc",
      id: "speech-to-text/streaming/quickstart",
    },
    {
      type: "doc",
      id: "speech-to-text/streaming/input",
    },
    {
      type: "doc",
      id: "speech-to-text/streaming/output",
    },
    {
      type: "doc",
      id: "speech-to-text/streaming/limits",
    },
    {
      type: "doc",
      id: "speech-to-text/streaming/realtime-diarization",
    },
    {
      type: "doc",
      id: "speech-to-text/streaming/speaker-identification",
    },
    {
      type: "doc",
      id: "speech-to-text/streaming/turn-detection",
    },
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "speech-to-text/streaming/guides",
        },
      ],
    },
    {
      type: "link",
      label: "API reference",
      href: "/api-ref/realtime-transcription-websocket",
    },
  ],
} as const;
